version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data  # Mapeamento do diretório do contêiner para o diretório do host
  web-users:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"  # Mapeamento da porta do contêiner para a porta do host
    volumes:
      - .:/app  # Mapeamento do diretório do projeto para o diretório do contêiner
    depends_on:
      - db  # Indica que este serviço depende do serviço 'db' 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq