# Generated by Django 4.2.3 on 2023-07-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='teste', max_length=50, unique=True),
        ),
    ]
